Test.Framework=Pytest+API+Selenium
CI.Platform=GitHub Actions
Test.Types=API Testing, UI Automation
Browsers=Chrome (Headless)
Target.URL=http://52.18.93.49:8080/
NocoDB.Image=yosefshawah/nocodb-custom:63b2bd2a8e66190f22334e1ab0bc760ac3fa5326-20250927-190805
Environment=PR-7
GitHub.Run.ID=18063767937
GitHub.Actor=yosefshawah
Workflow.Trigger=pull_request
Branch=feature/api-testing
Commit.SHA=63b2bd2a8e66190f22334e1ab0bc760ac3fa5326
Repository=yosefshawah/nocodb
Timestamp=2025-09-27 19:18:02 UTC
