Environment=PR-7
Test.Suite=both
Image.Tag=manual-run
NocoDB.URL=http://52.18.93.49:8080/
Debug.Mode=false
GitHub.Run.ID=18063401892
GitHub.Actor=yosefshawah
Workflow.Trigger=pull_request
Branch=feature/api-testing
Commit.SHA=5383fce037d80881b705b69a720468576248ab07
Repository=yosefshawah/nocodb
Timestamp=2025-09-27 18:39:16 UTC
